id: app
title: (CBP) IT System
type: project
version: 0.1.7.7
icon: cbp_app_icon.png
introduction:
  format: markdown
  template: IT System Questionnaires (Pilot) v0.1.7.7
output:
- id: fisma_ssp_template
  format: markdown
  template: |
    {% if not fisma_level.fisma_level %}
      The team is currently working on determining the system impact level.

    {% else %}
      Your system's FISMA Level is **{{fisma_level.fisma_level.text}}**.

      Information Types: {{fisma_level.information_types.text}}

      Impact Level based on Information Types: {{fisma_level.information_types_level.text}}

      PII Types: {{fisma_level.pii_types_collected.text}}

      PII Impact Level: {{fisma_level.pii_impact_level.text}}

      PHI? {{fisma_level.phi_has_any_phi.text}}

    PHI Impact Level: {{fisma_level.phi_impact_level.text}}
    {% endif %}

catalog:
  category: Draft
  description:
    long: |
      New Compliance App
      ==================

      Edit this Markdown file to provide a long description of your compliance app. The contents of this file will be displayed in the GovReady-Q Compliance Apps Catalog.
    short: IT System Questionnaires (Pilot) v0.1.7.7
  source_url: https://github.com/GovReady/cbp-big-q-apps
  status: stub
  vendor: CBP
  vendor_url: ~
  version: 0.1.7.7
questions:
- id: system_info
  title: System Profile
  type: module
  icon: system_info.png
  module-id: system_info
  group: System Info
- id: fisma_level
  title: Determine Your FISMA Level
  type: module
  icon: fisma_icon.png
  module-id: fisma_level
  group: System Categorization
- id: pta_intro
  title: Privacy Threshold Analysis (PTA) Overview
  type: module
  icon: PTA_icon_new.png
  module-id: pta_intro
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_purpose
  title: Purpose of the Information Collection
  type: module
  icon: PTA_icon_new.png
  module-id: pta_purpose
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_poc_details
  title: PTA POC Details
  type: module
  icon: PTA_icon_new.png
  module-id: pta_poc_details
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_ic_forms
  title: Questions
  type: module
  icon: PTA_icon_new.png
  module-id: pta_ic_forms
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_info_description
  title: Type of Information Collected
  type: module
  icon: PTA_icon_new.png
  module-id: pta_info_description
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_info_storage
  title: How Will DOS Store the Collected Information?
  type: module
  icon: PTA_icon_new.png
  module-id: pta_info_storage
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_printable
  title: Privacy Threshold Analysis Document
  type: module
  icon: PTA_icon_new.png
  module-id: pta_printable
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pas_intro
  title: Privacy Act Statement
  type: module
  icon: app.png
  module-id: pas_intro
  group: Privacy Act Statement (PAS)
  impute:
  - condition: project.pta_info_storage.PAS_upload_generate_choice != 'PAS_generate'
    value: ~
- id: pas_printable
  title: Privacy Act Statement Document
  type: module
  icon: app.png
  module-id: pas_printable
  group: Privacy Act Statement (PAS)
  impute:
  - condition: project.pta_info_storage.PAS_upload_generate_choice != 'PAS_generate'
    value: ~
- id: tp_introduction
  title: Test Introduction
  type: module
  module-id: tp_introduction
  icon: test_plan_new.png
  group: Test Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~
- id: tp_project_management
  title: Test Project Management
  type: module
  module-id: tp_project_management
  icon: test_plan_new.png
  group: Test Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~
- id: tp_test_environment
  title: Test Environment
  type: module
  module-id: tp_test_environment
  icon: test_plan_new.png
  group: Test Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~
- id: tp_printable
  title: Test Plan Document
  type: module
  module-id: tp_printable
  icon: test_plan_new.png
  group: Test Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~

- id: cp_introduction
  title: Contingency Plan Introduction
  type: module
  module-id: cp_introduction
  icon: cp_icon_detour.png
  group: Contingency Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~
- id: cp_questionnaire
  title: Contingency Plan Concept of Operations
  type: module
  module-id: cp_questionnaire
  icon: cp_icon_detour.png
  group: Contingency Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~
- id: cp_activation
  title: Contingency Plan Activation and Notification
  type: module
  module-id: cp_activation
  icon: cp_icon_detour.png
  group: Contingency Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~
- id: cp_recovery
  title: Contingency Plan Recovery
  type: module
  module-id: cp_recovery
  icon: cp_icon_detour.png
  group: Contingency Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~
- id: cp_reconstitution
  title: Contingency Plan Reconstitution
  type: module
  module-id: cp_reconstitution
  icon: cp_icon_detour.png
  group: Contingency Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~

- id: cp_general_info
  title: General Information
  type: module
  module-id: cp_general_info
  icon: cp_icon_detour.png
  group: Contingency Plan
  impute:
  - condition: 1 == 1
    value: ~

- id: cp_fedramp01
  title: Contingency Plan Document
  type: module
  module-id: cp_fedramp01
  icon: cp_icon_detour.png
  group: Contingency Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~

- id: cp_controls_80053r4
  title: 800-53r4 Controls
  type: module
  module-id: cp_controls_80053r4
  icon: cp_icon_detour.png
  group: Contingency Plan
  impute:
  - condition: 1 == 1
    value: ~

- id: se_cace_hosting_environ
  title: CACE – Hosting Environment
  type: module
  icon: se_cace_icon.png
  module-id: se_cace_hosting_environ
  group: Hosting Environment
  impute:
  - condition: project.system_info.system_hosting != 'cbp_cace'
    value: ~
- id: se_cace_auditing_splunk_elk
  title: CACE – Auditing (Splunk, ELK)
  type: module
  icon: aws_cloud_elk_icon.png
  module-id: se_cace_auditing_splunk_elk
  group: Hosting Environment
  impute:
  - condition: project.system_info.system_hosting != 'cbp_cace'
    value: ~
- id: se_cace_ci_cd_jenkins_gitlab_aqua_sonarqube
  title: CACE - CI/CD (Jenkins, GitLab, Aqua, SonarQube)
  type: module
  icon: se_cace_icon.png
  module-id: se_cace_ci_cd_jenkins_gitlab_aqua_sonarqube
  group: Hosting Environment
  impute:
  - condition: project.system_info.system_hosting != 'cbp_cace'
    value: ~
- id: se_ciso_policy_soc_stp
  title: CISO (Policy, SOC, STP)
  type: module
  icon: se_cace_icon.png
  module-id: se_ciso_policy_soc_stp
  group: Hosting Environment
  impute:
  - condition: project.system_info.system_hosting != 'cbp_cace'
    value: ~
- id: se_system_level
  title: System Level Controls
  type: module
  icon: se_cace_icon.png
  module-id: se_system_level
  group: Hosting Environment
  impute:
  - condition: project.system_info.system_hosting != 'cbp_cace'
    value: ~

- id: ssp_intro
  module-id: ssp_intro
  icon: ssp_icon.png
  title: System Security Plan
  type: module
  group: System Security Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~

deprecated-to-delete:
- id: cp_q_set_1
  module-id: cp_q_set_1
  icon: cp_icon_detour.png
  title: Question Set 1
  type: module
  group: Contingency Plan
  # impute:
  # - condition: project.system_info.operational_system != 'yes'
  #   value: ~
- id: cp_q_set_2
  module-id: cp_q_set_2
  icon: cp_icon_detour.png
  title: Question Set 2
  type: module
  group: Contingency Plan
  # impute:
  # - condition: project.system_info.operational_system != 'yes'
  #   value: ~

