id: app
title: (CBP) IT System
type: project
version: 0.1.2
icon: app.png
introduction:
  format: markdown
  template: IT System Questionnaires (Pilot)
catalog:
  category: Draft
  description:
    long: |
      New Compliance App
      ==================

      Edit this Markdown file to provide a long description of your compliance app. The contents of this file will be displayed in the GovReady-Q Compliance Apps Catalog.
    short: IT System Questionnaires (Pilot)
  source_url: https://github.com/GovReady/cbp-big-q-apps
  status: stub
  vendor: CBP
  vendor_url: ~
  version: 0.1.2

questions:

- id: system_info
  title: System Profile
  type: module
  module-id: system_info
  group: System Info

- id: se_cace_elk
  title: CACE ELK (Elastic, Logstach, Kibana) introduction
  type: module
  module-id: se_cace_elk
  icon: app.png
  group: Hosting Environment
  impute:
  - condition: project.system_info.system_hosting != 'cbp_cace'
    value: ~

- id: se_cace_elk_form
  title: View Test Plan (CACE-ELK)
  type: module
  module-id: se_cace_elk_form
  group: Hosting Environment - CACE
  placement: action-buttons

# - id: se_cbp_ds1
#   title: CBP DS1 (Data Center 1)
#   type: module
#   module-id: se_cbp_ds1
#   icon: app.png
#   group: Hosting Environment
#   impute:
#     - condition: "project.system_info.system_hosting != 'cbp_ds1'"
#       value: ~

- id: fisma_level
  title: Determine Your FISMA Level
  type: module
  module-id: fisma_level
  group: System Categorization

- id: pta_intro
  title: Privacy Threshold Analysis (PTA) Overview
  type: module
  module-id: pta_intro
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_purpose
  title: Purpose of the Information Collection
  type: module
  module-id: pta_purpose
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_poc_details
  title: PTA POC Details
  type: module
  module-id: pta_poc_details
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_ic_forms
  title: Questions
  type: module
  module-id: pta_ic_forms
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_info_description
  title: Type of Information Collected
  type: module
  module-id: pta_info_description
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_info_storage
  title: How Will DOS Store the Collected Information?
  type: module
  module-id: pta_info_storage
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_form
  title: View PTA Artifact
  type: module
  module-id: pta_form
  group: PTA (Privacy Threshold Analysis)
  placement: action-buttons

- id: tp_part1
  title: Test Plan Part 1 Module
  type: module
  module-id: tp_part1
  group: Test Plan
  impute:
  - condition: 1 == 1
    value: ~
- id: tp_part2
  title: Test Plan Part 2 Module
  type: module
  module-id: tp_part2
  group: Test Plan
  impute:
  - condition: 1 == 1
    value: ~

- id: tp_introduction
  title: Test Introduction
  type: module
  module-id: tp_introduction
  group: Test Plan
  impute:
  - condition: 1 == 1
    value: ~

- id: tp_project_management
  title: Test Project Management
  type: module
  module-id: tp_project_management
  group: Test Plan
  impute:
  - condition: 1 == 1
    value: ~

- id: tp_roles_and_responsibilities
  title: Test Roles and Responsibilities
  type: module
  module-id: tp_roles_and_responsibilities
  group: Test Plan
  impute:
  - condition: 1 == 1
    value: ~

- id: tp_test_environment
  title: Test Environment
  type: module
  module-id: tp_test_environment
  group: Test Plan
  impute:
  - condition: 1 == 1
    value: ~

- id: cp_q_set_1
  module-id: cp_q_set_1
  title: Question Set 1
  type: module
  group: Contingency Plan
- id: cp_q_set_2
  module-id: cp_q_set_2
  title: Question Set 2
  type: module
  group: Contingency Plan


output:

- id: fisma_ssp_template
  format: markdown
  template: |
    {% if not fisma_level.fisma_level %}
      The team is currently working on determining the system impact level.

    {% else %}
      Your system's FISMA Level is **{{fisma_level.fisma_level.text}}**.

      Information Types: {{fisma_level.information_types.text}}

      Impact Level based on Information Types: {{fisma_level.information_types_level.text}}

      PII Types: {{fisma_level.pii_types_collected.text}}

      PII Impact Level: {{fisma_level.pii_impact_level.text}}

      PHI? {{fisma_level.phi_has_any_phi.text}}

    PHI Impact Level: {{fisma_level.phi_impact_level.text}}
    {% endif %}


- id: cbp_tp
  format: markdown
  title: CBP Test Plan
  # filename: templates/tp_cbp_tp.md
  placement: action-buttons
  template: "<style type=\"text/css\" scoped>\n    h2 { border-bottom:1px solid #888;
    }\n    h3 { border-bottom: 0.5px solid #aaa; }\n    h4 { margin-top: 15px; font-weight:
    bold; font-size: 1em; }\n    blockquote { color: #666; font-size:0.8em; margin:
    0 10px; }\n    .notice {color: red; font-size:3.0em; text-align:center; transform:
    scaleY(.85);\n    font-weight: bold;}\n    table, th, td { border: 1px solid #888;
    }\n    th, td { padding: 15px; text-align: left;}\n</style>\n\n<center>\n(DRAFT)
    CBP Test Plan 2\n</center>\n\n<div style=\"font-weight: bold;\">\n  <p style=\"text-align:
    center;\">\n    SYSTEM INFORMATION\n  </p>\n</div>\n\n<div>\n  <p>{{project.system_info.system_short_name}}
    is a {{project.system_info.system_type.text}} hosted in the {{project.system_info.system_hosting.text}}
    environment.\n  </p>\n  <p>\n    {{project.system_info.system_description}}\n
    \ </p>\n</div>\n\n<div>\n  <p>\n    {{project.se_cace_elk.output_documents.nist_80053rev4_ssp_ac_6_9}}\n\n
    <hr>
    <div>
      <h3>Test Plan Introduction</h3>{{project.se_cace_elk}}{% if project.se_cace_elk %}
      {% for od in project.se_cace_elk.output_documents %}
        <div style=\"margin: 12px 0 0 0;\">
            {{project.se_cace_elk.output_documents[od]}}
        </div>
        <small style=\"color: #aaa;\">{{od}}</small>
      {% endfor %}
      {% endif %}
    </div>
    "


- id: nist_80053rev4_ssp_ac_6_9
  title: NIST 800-53 rev4 SSP AC-6 (9)
  format: markdown
  template: >2

    CACE (ELK): ELK is implemented to audit the execution of privileged functionality
    at the application level. The ISSO has configured ELK such that privileged functionality
    (e.g. ability to configure access permissions) has been identified, logged, and
    audited.

- id: nist_80053rev4_ssp_ac_6_9_test
  title: NIST 800-53 rev4 SSP AC-6(9) Test
  format: markdown
  template: >2

    System-generated audit report identifying privileged functions are logged and audited independently. CACE UAR forms are used to track user and level of access. Kibana stores all activity logs and can be queried for audit information.

- id: nist_80053rev4_ssp_au_12_a_2
  title: NIST 800-53 rev4 SSP AU-12(a)[2]
  format: markdown
  template: |2

    CACE (ELK): Audit records for the application are generated by Kibana.

- id: nist_80053rev4_ssp_au_12_a_2_test
  title: NIST 800-53 rev4 SSP AU-12(a)[2] Test
  format: markdown
  template: |2

    System-generated audit log report for specific criteria.


- id: nist_80053rev4_ssp_au_12_b_2
  title: NIST 800-53 rev4 SSP AU-12(b)[2]
  format: markdown
  template: |2

    CACE (ELK): The Kibana dashboard has been configured by the ISSO such that the auditor role can isolate a particular application component and run reports and view logs on that specific component.

- id: nist_80053rev4_ssp_au_12_b_2_test
  title: NIST 800-53 rev4 SSP AU-12(a)[2] Test
  format: markdown
  template: |2

    Kibana configuration settings that offer the ISSO the capability to isolate a particular application component and run reports and view logs on that specific component.

- id: nist_80053rev4_ssp_au_12_c
  title: NIST 800-53 rev4 SSP AU-12(c)
  format: markdown
  template: |2

    CACE (ELK): Audit records for the application are generated by Kibana.

- id: nist_80053rev4_ssp_au_12_c_test
  title: NIST 800-53 rev4 SSP AU-12(c) Test
  format: markdown
  template: |2

    Kibana audit record.

- id: nist_80053rev4_ssp_au_12_dhs_5_3_g
  title: NIST 800-53 rev4 SSP AU-12 (DHS-5.3.g)
  format: markdown
  template: |2

    CACE (ELK): ELK has been configured such that whenever an audit processing failure occurs on logs from the application layer error messages are automatically emailed to the CBP SOD. If audit capacity is reached the application logs are configured to overwrite the oldest data first. 

- id: nist_80053rev4_ssp_au_12_dhs_5_3_g_test
  title: NIST 800-53 rev4 SSP AU-12 (DHS-5.3.g) Test
  format: markdown
  template: |2

    ELK configuration settings that demonstrate contingency operation methods to capture audit logs, and notify administrators in event of processing failure.

- id: nist_80053rev4_ssp_au_2_a_2
  title: NIST 800-53 rev4 SSP AU-2 (a)[2]
  format: markdown
  template: |2

    "CACE (ELK): ELK provides the auditing capability on behalf of the system's application layer."

- id: nist_80053rev4_ssp_au_2_a_2_test
  title: NIST 800-53 rev4 SSP AU-2 (a)[2] Test
  format: markdown
  template: |2

    "ELK configuration settings."

# In progress
# - id: nist_80053rev4_ssp_au_2_a_b
#   title: NIST 800-53 rev4 SSP AU-2 (a)[b]
#   format: markdown
#   template: |2

#     "CACE (ELK): ELK provides the auditing capability on behalf of the system's application layer."


# - id: nist_80053rev4_ssp_si_4_part_tbd
#   title: NIST 800-53 rev4 SSP SI-4 [PART_TBD]
#   format: markdown
#   filename: templates/nist_80053rev4_ssp_SI-4.md
#   template: |2

#     CACE (ELK): Access to the ELK management consoles and report are controlled through strong authentication and well defined access control procedures.
# - id: nist_80053rev4_ssp_si_4_part_tbd
#   title: NIST 800-53 rev4 SSP SI-4 [PART_TBD]
#   format: markdown
#   filename: templates/nist_80053rev4_ssp_SI-4.md
#   template: |2

#     CACE (ELK): Access to the ELK management consoles and report are controlled through strong authentication and well defined access control procedures.
# - id: nist_80053rev4_ssp_si_4_part_tbd
#   title: NIST 800-53 rev4 SSP SI-4 [PART_TBD]
#   format: markdown
#   filename: templates/nist_80053rev4_ssp_SI-4.md
#   template: |2

#     CACE (ELK): Access to the ELK management consoles and report are controlled through strong authentication and well defined access control procedures.


# - id: nist_80053rev4_ssp_si_4_part_tbd
#   title: NIST 800-53 rev4 SSP SI-4 [PART_TBD]
#   format: markdown
#   filename: templates/nist_80053rev4_ssp_SI-4.md
#   template: |2

#     CACE (ELK): Access to the ELK management consoles and report are controlled through strong authentication and well defined access control procedures.
# - id: nist_80053rev4_ssp_si_4_part_tbd
#   title: NIST 800-53 rev4 SSP SI-4 [PART_TBD]
#   format: markdown
#   filename: templates/nist_80053rev4_ssp_SI-4.md
#   template: |2

#     CACE (ELK): Access to the ELK management consoles and report are controlled through strong authentication and well defined access control procedures.
# - id: nist_80053rev4_ssp_si_4_part_tbd
#   title: NIST 800-53 rev4 SSP SI-4 [PART_TBD]
#   format: markdown
#   filename: templates/nist_80053rev4_ssp_SI-4.md
#   template: |2

#     CACE (ELK): Access to the ELK management consoles and report are controlled through strong authentication and well defined access control procedures.
# - id: nist_80053rev4_ssp_si_4_part_tbd
#   title: NIST 800-53 rev4 SSP SI-4 [PART_TBD]
#   format: markdown
#   filename: templates/nist_80053rev4_ssp_SI-4.md
#   template: |2

#     CACE (ELK): Access to the ELK management consoles and report are controlled through strong authentication and well defined access control procedures.



