id: app
title: (CBP) IT System
type: project
version: 0.1.5.0
icon: app.png
introduction:
  format: markdown
  template: IT System Questionnaires (Pilot) v0.1.5.0
output:
- id: fisma_ssp_template
  format: markdown
  template: |
    {% if not fisma_level.fisma_level %}
      The team is currently working on determining the system impact level.

    {% else %}
      Your system's FISMA Level is **{{fisma_level.fisma_level.text}}**.

      Information Types: {{fisma_level.information_types.text}}

      Impact Level based on Information Types: {{fisma_level.information_types_level.text}}

      PII Types: {{fisma_level.pii_types_collected.text}}

      PII Impact Level: {{fisma_level.pii_impact_level.text}}

      PHI? {{fisma_level.phi_has_any_phi.text}}

    PHI Impact Level: {{fisma_level.phi_impact_level.text}}
    {% endif %}
- id: nist_80053rev4_ssp_ac_6_9
  title: NIST 800-53 rev4 SSP AC-6 (9)
  format: markdown
  template: >2

    CACE (ELK): ELK is implemented to audit the execution of privileged functionality
    at the application level. The ISSO has configured ELK such that privileged functionality
    (e.g. ability to configure access permissions) has been identified, logged, and
    audited.
- id: nist_80053rev4_ssp_ac_6_9_test
  title: NIST 800-53 rev4 SSP AC-6(9) Test
  format: markdown
  template: >2

    System-generated audit report identifying privileged functions are logged and
    audited independently. CACE UAR forms are used to track user and level of access.
    Kibana stores all activity logs and can be queried for audit information.
- id: nist_80053rev4_ssp_au_12_a_2
  title: NIST 800-53 rev4 SSP AU-12(a)[2]
  format: markdown
  template: |2

    CACE (ELK): Audit records for the application are generated by Kibana.
- id: nist_80053rev4_ssp_au_12_a_2_test
  title: NIST 800-53 rev4 SSP AU-12(a)[2] Test
  format: markdown
  template: |2

    System-generated audit log report for specific criteria.
- id: nist_80053rev4_ssp_au_12_b_2
  title: NIST 800-53 rev4 SSP AU-12(b)[2]
  format: markdown
  template: |2

    CACE (ELK): The Kibana dashboard has been configured by the ISSO such that the auditor role can isolate a particular application component and run reports and view logs on that specific component.
- id: nist_80053rev4_ssp_au_12_b_2_test
  title: NIST 800-53 rev4 SSP AU-12(a)[2] Test
  format: markdown
  template: |2

    Kibana configuration settings that offer the ISSO the capability to isolate a particular application component and run reports and view logs on that specific component.
- id: nist_80053rev4_ssp_au_12_c
  title: NIST 800-53 rev4 SSP AU-12(c)
  format: markdown
  template: |2

    CACE (ELK): Audit records for the application are generated by Kibana.
- id: nist_80053rev4_ssp_au_12_c_test
  title: NIST 800-53 rev4 SSP AU-12(c) Test
  format: markdown
  template: |2

    Kibana audit record.
- id: nist_80053rev4_ssp_au_12_dhs_5_3_g
  title: NIST 800-53 rev4 SSP AU-12 (DHS-5.3.g)
  format: markdown
  template: "\nCACE (ELK): ELK has been configured such that whenever an audit processing
    failure occurs on logs from the application layer error messages are automatically
    emailed to the CBP SOD. If audit capacity is reached the application logs are
    configured to overwrite the oldest data first. \n"
- id: nist_80053rev4_ssp_au_12_dhs_5_3_g_test
  title: NIST 800-53 rev4 SSP AU-12 (DHS-5.3.g) Test
  format: markdown
  template: |2

    ELK configuration settings that demonstrate contingency operation methods to capture audit logs, and notify administrators in event of processing failure.
- id: nist_80053rev4_ssp_au_2_a_2
  title: NIST 800-53 rev4 SSP AU-2 (a)[2]
  format: markdown
  template: |2

    "CACE (ELK): ELK provides the auditing capability on behalf of the system's application layer."
- id: nist_80053rev4_ssp_au_2_a_2_test
  title: NIST 800-53 rev4 SSP AU-2 (a)[2] Test
  format: markdown
  template: |2

    "ELK configuration settings."


- id: cp_ssp_nist80053r4_AC_2
  title: NIST 800-53r4 AC-2 Account Management
  format: markdown
  template: |
    {% if project.general_info.exists != "yes" %}The following controls will be in place with the completion of the Rules of Behavior.{% endif %}

    {{project.rob.applies_to}}

    {{project.general_info.obtain}}

- id: cp_ssp_nist80053r4_AT_2
  title: NIST 800-53r4 AT-2 Security Awareness Training
  format: markdown
  template: >+
    {% if project.general_info.exists != "yes" %}The following controls will be in place with the completion of the Rules of Behavior.{% endif %}

    The organization Rules of Behavior (officially titled _{{project.general_info.official_name}}_) {% if project.general_info.exists == "yes" %}describes{% else %}will describe{% endif %} general responsibilities and expected media protection behavior of personnel with access to organization IT resources.

- id: cp_ssp_nist80053r4_MP_1
  title: NIST 800-53r4 MP-1 Media Protection Policy And Procedures
  format: markdown
  template: >+
    {% if project.general_info.exists != "yes" %}The following controls will be in place with the completion of the Rules of Behavior.{% endif %}

    Media protection policy and procedures {% if project.general_info.exists == "yes" %}are{% else %}will be{% endif %} documented in System Security Plan and the IT System Rules of Behavior. These documents provide the roles and responsibilities for media protection policies and procedures as it pertains to clearing, sanitization, disposal, and storage of media.

- id: cp_ssp_nist80053r4_PL_4
  title: NIST 800-53r4 PL-4 Rules of Behavior
  format: markdown
  template: >+
    {% if project.general_info.exists == 'yes' %}

    {{project.general_info.organization}} implements Control PL-4 with its Rules of Behavior document
    officially titled _{{project.general_info.official_name}}_.
    The Rules of Behavior describes users' responsibilities and expected behavior when using {{organization}} IT resources.
    {{project.rob.applies_to}}

    The Rules of Behavior doucement is maintained as a {{project.general_info.source_repo.text}}. {{project.general_info.source_repo_identifier}}

    The {{project.general_info.role_owner}} maintains the Rules of Behavior and reviews
    the Rules of Behavior {{project.general_info.review_frequency.text}}.


    {{project.general_info.obtain}}

    {% if project.general_info.source_public == 'yes' %}
    The Rules of Behavior is available publicly online at [{{project.general_info.source_public_url}}]({{project.general_info.source_public_url}}).
    {% else %}
    The Rules of Behavior is not available publicly online.
    {% endif %}

    {% else %}

    {{project.general_info.organization}} will implement Control PL-4 with Rules of Behavior document
    officially titled _{{project.general_info.official_name}}_.
    The Rules of Behavior will describe users' responsibilities and expected behavior when using {{organization}} IT resources.
    {{project.rob.applies_to}}

    The Rules of Behavior doucement will be maintained as a {{project.general_info.source_repo.text}}. {{project.general_info.source_repo_identifier}}

    The {{project.general_info.role_owner}} will maintain the Rules of Behavior and review
    them {{project.general_info.review_frequency.text}}.


    {{project.general_info.obtain}}

    {% if project.general_info.source_public == 'yes' %}
    The Rules of Behavior will be available publicly online at [{{project.general_info.source_public_url}}]({{project.general_info.source_public_url}}).
    {% else %}
    The Rules of Behavior will not be available publicly online.
    {% endif %}

    {% endif %}

- id: cp_ssp_nist80053r4_PS_6
  title: NIST 800-53r4 PS-6 Access Agreements
  format: markdown
  template: >+
    {% if project.general_info.exists != "yes" %}The following controls will be in place with the completion of the Rules of Behavior.{% endif %}

    The Department {% if project.general_info.exists == "yes" %}has implemented{% else %}will implement{% endif %} a formalized process for user account administration which requires applicable personnel requesting access to organization IT resources read and agree to the Rules of Behavior found in the document officially titled _{{project.general_info.official_name}}_.

- id: cp_ssp_nist80053r4_PS_7
  title: NIST 800-53r4 PS-7 Third-Party Personnel Security
  format: markdown
  template: >+
    {% if project.general_info.exists != "yes" %}The following controls will be in place with the completion of the Rules of Behavior.{% endif %}

    All contractor support personnel are required to meet the same personnel security policy requirements as {{organization}} personnel who have privileged access to the IT System. Third party providers {% if project.general_info.exists == "yes" %}are required{% else %}will be required{% endif %} to review and sign the Rules of Behavior found in the document officially titled _{{project.general_info.official_name}}_ prior to being granted access to the system.

- id: cp_ssp_nist80053r4_SA_7
  title: NIST 800-53r4 SA-7 User-Installed Software
  format: markdown
  template: |+
    {% if project.general_info.exists != "yes" %}The following controls will be in place with the completion of the Rules of Behavior.{% endif %}

    {{organization}} {% if project.general_info.exists == "yes" %}uses{% else %}will use{% endif %} the Rules of Behavior (officially titled _{{project.general_info.official_name}}_) to document and set forth appropriate activities on an information system.


catalog:
  category: Draft
  description:
    long: |
      New Compliance App
      ==================

      Edit this Markdown file to provide a long description of your compliance app. The contents of this file will be displayed in the GovReady-Q Compliance Apps Catalog.
    short: IT System Questionnaires (Pilot) v0.1.5.0
  source_url: https://github.com/GovReady/cbp-big-q-apps
  status: stub
  vendor: CBP
  vendor_url: ~
  version: 0.1.5.0
questions:
- id: system_info
  title: System Profile
  type: module
  module-id: system_info
  group: System Info
- id: se_cace_elk
  title: CACE ELK (Elastic, Logstach, Kibana) introduction
  type: module
  module-id: se_cace_elk
  icon: app.png
  group: Hosting Environment
  impute:
  - condition: project.system_info.system_hosting != 'cbp_cace'
    value: ~
- id: fisma_level
  title: Determine Your FISMA Level
  type: module
  module-id: fisma_level
  group: System Categorization
- id: pta_intro
  title: Privacy Threshold Analysis (PTA) Overview
  type: module
  module-id: pta_intro
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_purpose
  title: Purpose of the Information Collection
  type: module
  module-id: pta_purpose
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_poc_details
  title: PTA POC Details
  type: module
  module-id: pta_poc_details
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_ic_forms
  title: Questions
  type: module
  module-id: pta_ic_forms
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_info_description
  title: Type of Information Collected
  type: module
  module-id: pta_info_description
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_info_storage
  title: How Will DOS Store the Collected Information?
  type: module
  module-id: pta_info_storage
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: pta_form
  title: Privacy Threshold Analysis Document
  type: module
  module-id: pta_form
  group: PTA (Privacy Threshold Analysis)
  impute:
  - condition: project.system_info.system_personal_data != 'yes'
    value: ~
- id: tp_introduction
  title: Test Introduction
  type: module
  module-id: tp_introduction
  group: Test Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~
- id: tp_project_management
  title: Test Project Management
  type: module
  module-id: tp_project_management
  group: Test Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~
- id: tp_test_environment
  title: Test Environment
  type: module
  module-id: tp_test_environment
  group: Test Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~
- id: tp_plan
  title: Test Plan Document
  type: module
  module-id: tp_document
  group: Test Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~

- id: cp_questionnaire
  title: Contingency Plan (Edit by Section)
  type: module
  module-id: cp_questionnaire
  group: Contingency Plan
  impute:
  - condition: 1 == 1
    value: ~

- id: cp_general_info
  title: General Information
  type: module
  module-id: cp_general_info
  group: Contingency Plan
  impute:
  - condition: 1 == 1
    value: ~

- id: cp_fedramp01
  title: Contingency Plan Document
  type: module
  module-id: cp_fedramp01
  group: Contingency Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~

- id: cp_controls_80053r4
  title: 800-53r4 Controls
  type: module
  module-id: cp_controls_80053r4
  group: Contingency Plan
  impute:
  - condition: 1 == 1
    value: ~

- id: ssp_intro
  module-id: ssp_intro
  title: System Security Plan
  type: module
  group: System Security Plan
  impute:
  - condition: project.system_info.operational_system != 'yes'
    value: ~

deprecated-to-delete:
- id: cp_q_set_1
  module-id: cp_q_set_1
  title: Question Set 1
  type: module
  group: Contingency Plan
  # impute:
  # - condition: project.system_info.operational_system != 'yes'
  #   value: ~
- id: cp_q_set_2
  module-id: cp_q_set_2
  title: Question Set 2
  type: module
  group: Contingency Plan
  # impute:
  # - condition: project.system_info.operational_system != 'yes'
  #   value: ~

