id: tp_test_environment
title: Test Environment
internal:
  snippets:
  - snippet: |
      Update the Test Environment snippet
introduction:
  format: markdown
  template: Update the Test Environment introduction content.
output: []
questions:
- id: q1
  title: Test completion criteria
  prompt: "What is the Test Completion Criteria?\r\n\r\nThe team needs to agree up\
    \ front the definition of a successful. \r\n\r\nIf all the high level bugs have\
    \ been addressed we can move forward with deployment."
  type: longtext
- id: q2
  type: text
  title: New Question Title 2
  prompt: Enter some text.
